import backtrader as bt
from app.backtest.strategies.base import BaseStrategy

class SignalCaptureStrategy(BaseStrategy):
    """
    A wrapper strategy that captures buy/sell signals generated by the underlying strategy logic.
    Used for paper trading to intercept signals without executing them in the simulation broker.
    """
    
    def __init__(self, target_strategy_cls, **kwargs):
        super().__init__()
        # Initialize the target strategy logic
        # We mixin the target strategy or delegate to it?
        # Delegation is hard because Strategy expects to be the main class.
        # Mixin/Inheritance is better. 
        # But we want to run *any* strategy.
        
        # Alternative: We don't wrap. We use an Analyzer.
        # But Analyzer runs *after* the strategy step.
        pass

# Better approach: Use a custom Analyzer that records the orders created in the last step.
class SignalAnalyzer(bt.Analyzer):
    """
    Analyzer that captures orders created during the backtest.
    """
    def __init__(self):
        self.orders = []

    def notify_order(self, order):
        if order.status == order.Submitted:
            self.orders.append(order)

    def get_analysis(self):
        return self.orders
